name: sk-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow=2.13
  - cudatoolkit=11.8  # comment: remove if CPU
  - pip
  - pip:
      - tensorflow-addons==0.22.0
      - performer-keras==0.2.5
      - numpy==1.24.3
      - pandas==2.1.0
      - matplotlib==3.8.0
      - scikit-learn==1.3.0
      - astropy==5.3.4
      - sunpy==5.0.0
      - h5py==3.10.0
      - tqdm==4.66.1 