name: informer-training
description: "Train the Informer model on A100 GPUs using Replicate. The model script automatically downloads the dataset from Google Drive if it is not already present."
gpu: a100
build:
  dockerfile: Dockerfile
command: >
  python models/replicate/informer.py --train
outputs:
  - final_model.pth
  - informer_scripted.pth