name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps
      run: |
        python -m pip install --upgrade pip

        # Install required dependencies explicitly with verbose output
        python -m pip install --verbose tensorflow numpy pandas matplotlib h5py scikit-learn

        # Install test dependencies
        python -m pip install pytest pytest-cov black flake8

    # ------- 1 Format & Lint ----------------------------------
    - name: Format code with black
      run: |
        # Auto-format instead of checking
        black solar_knowledge tests

    - name: Lint with flake8
      run: |
        flake8 solar_knowledge tests

    # ------- 2 Unit tests -------------------------------------
    - name: Run pytest with coverage
      env:
        TF_CPP_MIN_LOG_LEVEL: "3"
      run: |
        # Only run tests in the tests/ directory, excluding archive/
        pytest tests/ --cov=solar_knowledge --cov-report=xml --cov-report=term -v

    # Save coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false

    # ------- 3 Smoke training (1 epoch on tiny data) ----------
    - name: Smoke train SolarKnowledge
      run: |
        # Ensure the dataset directory exists
        mkdir -p datasets/tiny_sample

        # Generate the sample dataset if it doesn't exist
        if [ ! -f datasets/tiny_sample/sharp_ci_sample.h5 ]; then
          python scripts/generate_tiny_sample.py
        fi

        python -m solar_knowledge.smoke_train \
          --data-dir datasets/tiny_sample \
          --epochs 1
