name: Nightly eval

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC daily
  workflow_dispatch:      # manual trigger

jobs:
  eval:
    runs-on: ubuntu-latest
    timeout-minutes: 240   # guardrail
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: sk-env

    - name: Download model artefact
      uses: actions/download-artifact@v4
      with:
        name: solarknowledge-latest
        path: models/

    - name: Run full inference
      shell: bash -l {0}
      run: |
        python -m solar_knowledge.eval_full \
          --weights models/solarknowledge-latest.h5 \
          --split 2023-05:2025-04

    - name: Archive nightly metrics
      uses: actions/upload-artifact@v4
      with:
        name: nightly-metrics
        path: reports/nightly_*.json 