name: Publish Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'solar_knowledge/**'
      - 'docs/**'
      - '.github/workflows/publish-docs.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme myst-parser

    - name: Build documentation
      run: |
        mkdir -p docs/api
        sphinx-apidoc -o docs/api solar_knowledge
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
